[localhost]
# run `which python` and replace the value in ansible_python_interpreter
127.0.0.1 ansible_python_interpreter=/usr/bin/python

[webservers]
18.184.148.67 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=aws-staging-private.pem
