---
- name: Create AWS instance
  hosts: localhost
  connection: local
  gather_facts: false
  remote_user: ubuntu
  vars_files:
    - group_vars/all.yml
  roles:
    - create

- name: Add user keys
  hosts: all
  #become: yes
  #become_user: root
  remote_user: ubuntu
  roles:
    - users
