---
- name: Create AWS instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  remote_user: ubuntu
  vars_files:
    - group_vars/all.yml
  roles:
    - create

- name: Add user keys
  hosts: ec2_hosts
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  roles:
    - users
