---
- name: Create EC2 instance
  ec2:
    key_name: "{{ project_name }}-{{ env }}-key"
    region: "{{ aws_region }}"
    group_id: "{{ basic_firewall.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    instance_tags:
      env: "{{ env }}"
    count_tag: env
    exact_count: 1
  register: ec2

- name: Save IP to inventory file
  copy: content="[webservers]{{'\n'}}{{ item.public_ip }}" dest=./{{ env }}
  with_items: "{{ ec2.tagged_instances }}"

- name: Add IP to ec2_hosts group
  add_host: hostname={{ item.public_ip }} groups=ec2_hosts
  with_items: "{{ ec2.tagged_instances }}"
