---
- name: Create EC2 instance
  ec2:
    key_name: "{{ project_name }}-{{ env }}-key"
    region: "{{ aws_region }}"
    group_id: "{{ basic_firewall.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    instance_tags:
      env: "{{ env }}"
    count_tag: env
    exact_count: 1
  register: ec2

- name: Add the newly created EC2 instance(s) to host group
  lineinfile: path={{ hostpath }}
              regexp={{ item.public_ip }}
              insertafter="[webserver]"
              line="{{ item.public_ip }} {{hoststring}}"
              state=present
  with_items: "{{ ec2.tagged_instances }}"

- wait_for: path={{ hostpath }} search_regex={{hoststring}}

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: "{{ ec2.tagged_instances }}"

- name: Add IP to ec2_hosts group
  add_host: hostname={{ item.public_ip }} groups=ec2_hosts
  with_items: "{{ ec2.tagged_instances }}"
