# Build project from source
---
# FIXME Blocks on this part of the code
# Had a fix for it but blew it since I forgot to add it to the script
- name: Install packages based on package.json
  npm:
    executable: /usr/bin/npm --unsafe-perm=true --allow-root
    path: "{{ app_path }}/client"

- name: Build Angular project for TST server
#  command: ng build --prod --aot --env:prod
  become: yes
  command: sudo ng build --output-path=/var/www/html/{{ application_name }}/ --delete-output-path=false --base-href /{{ application_name }}/
  args:
    chdir: "{{ app_path }}/client"
#  environment:
#    PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/home/jeff/.nvm/versions/node/v7.9.0/bin/

- name: Open up rights to be able to view website from http://2.2.2.2/volvovalor
  file: 
    dest: "/var/www/html/{{ application_name }}/" 
    owner: "nobody" 
    group: appgrp
    mode: '777'
    recurse: yes