---
# Need PM2 for when an express server needs to run
# Is not required for Angular application because it gets built and deployed to be hosted by Nginx
- name: PM2 | Install PM2
  become: yes
  npm: name=pm2 global=yes
  tags: pm2

- name: start application with pm2
  command: pm2 start {{ app_path }}/{{ server_file}}
  ignore_errors: yes
  become: yes
  tags: pm2
